version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # 80 là port của nginx trong container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # nếu bạn có custom nginx.conf
    restart: unless-stopped
